# 占位符
## pass
pass 是一个空语句，不做任何事情，主要用于语法上需要有语句的地方占位。例如，在定义一个空函数、类、循环或条件语句块时使用，以保持代码结构的完整，避免语法错误。

```python
# 函数
def my_function():
    pass

# 类
class MyClass:
    def __init__(self):
        pass

# while循环
while condition:
    pass

# for循环
for i in range(5):
    pass

# 条件语句
if condition:
    pass
else:
    pass

# 异常处理
try:
    # 尝试执行可能会引发异常的代码
    pass
except SomeException:
    # 处理特定异常的代码
    pass
else:
    # 如果没有发生异常，则执行的代码
    pass
finally:
    # 无论是否发生异常，都会执行的代码
    pass
```



## 下划线(_)

1. **作为迭代器的占位符**: 当你需要迭代一个可迭代对象，但不关心具体的迭代元素时，可以使用 `_`。 
```python
# for循环
for _ in range(5):
    print("Hello")

# 列表生成器
new_ls = [0 for _ in range(5)]
print(new_ls)  # 输出：[0, 0, 0, 0, 0]
```

这里 `_` 仅仅用来计数，而不使用循环变量的值。 

2. **忽略函数返回值**: 当调用一个函数但不关心其返回值时，可以将返回值赋给 `_`。 
```python
_, b = func()
```





# 条件语句

1、可有零个或多个 elif 部分，else 部分也是可选的。

2、关键字 'elif' 是 'else if' 的缩写，用于避免过多的缩进。

3、if ... elif ... elif ... 序列可以当作其它语言中 switch 或 case 语句的替代品。

4、条件可以是任意表达式，包括但不限于比较运算符（如 ==, !=, <, >, <=, >=），逻辑运算符（如 and, or, not），成员资格测试（如 in，not in），以及其他能够返回布尔值的操作。



```python
x = 2

if x > 5:
    print("x 大于 5")
elif x == 5:
    print("x 等于 5")
else:
    print("x 小于 5")
```



## 三元运算符

```python
print("yes") if x > 5 else print("no")

res = "yes" if x > 1 else "no"
```



## if ... if ... 和 if ... elif ... 区别

- if ... if ... ：都会判断

```python
x = 5

if x > 1:
    print("x > 1")  # 执行

if x > 2:
    print("x > 2")  # 执行
    
"""
x > 1
x > 2
"""
```

- if ... elif ... ：如果if为真，elif不再判断

```python
x = 5

if x > 1:
    print("x > 1")  # 执行

elif x > 2:
    print("x > 2")  # 不执行
    
"""
x > 1
"""
```





# 循环语句

Python 提供了 `for` 和 `while` 循环结构来进行重复执行代码。

## for 循环

- 已知循环次数，遍历序列。

```python
numbers = [1, 2, 3, 4, 5]
for num in numbers:
    print(num, end=" ")
    
"""
1 2 3 4 5 
"""
```



- 带索引，使用 `enumerate` 函数。

```python
  # 默认索引从0开始
  fruits = ['苹果', '香蕉', '樱桃']
  
  for i, fruit in enumerate(fruits):
      print(f"索引: {i}, 水果: {fruit}")
      
  """
  Index: 0, Fruit: apple
  Index: 1, Fruit: banana
  Index: 2, Fruit: cherry
  """
      
  
  # 使用`start`参数指定索引的起始值
  for i, fruit in enumerate(fruits, start=1):
      print(f"索引: {i}, 水果: {fruit}")
      
  """
  Index: 1, Fruit: apple
  Index: 2, Fruit: banana
  Index: 3, Fruit: cherry
  """
```



## while循环

- 未知循环次数，满足特定条件执行。

```python
num = 1
while num != 'q':
    if num == 5:
        break
    print(num, end=" ")
    num += 1
    
"""
1 2 3 4 
"""
```



- 无限循环

```python
while True:
    pass
```











# break语句

`break` 用于跳出最近的 for 或 while 循环。

```python
# 单层循环

for i in range(5):
    if i == 3:
        break
    print(i, end=' ')
    
"""
0 1 2 
"""
```



```python
# 双层循环-外循环体中终止外循环

import string

for i in range(4):
    if i == 2:
        break
    print(i, end=' ')
    
    for letter in string.ascii_lowercase[:3]:
        print(letter, end=' ')
        
"""
0 a b c 1 a b c 
"""
```



```python
# 双层循环-内循环体中终止外循环

import string

for i in range(4):
    print(i, end=' ')

    for letter in string.ascii_lowercase[:3]:
        if i == 1:
            break
        print(letter, end=' ')
        
"""
0 a b c 1 2 a b c 3 a b c 
"""
```



```python
# 双层循环-内循环体中终止内循环

import string

for i in range(4):
    print(i, end=' ')

    for j, letter in enumerate(string.ascii_lowercase[:3]):
        if j == 1:
            break
        print(letter, end=' ')
        
"""
0 a 1 a 2 a 3 a 
"""
```





# continue语句

`continue` 用于跳过 for 或 while 循环的本次迭代。

```python
# 单层循环

for i in range(5):
    if i == 3:
        continue
    print(i, end=' ')
    
"""
0 1 2 4 
"""
```



```python
# 双层循环-外循环体中终止外循环

import string

for i in range(4):
    if i == 2:
        continue
    print(i, end=' ')
    
    for letter in string.ascii_lowercase[:3]:
        print(letter, end=' ')
        
"""
0 a b c 1 a b c 3 a b c 
"""
```



```python
# 双层循环-内循环体中终止外循环

import string

for i in range(4):
    print(i, end=' ')

    for letter in string.ascii_lowercase[:3]:
        if i == 1:
            continue
        print(letter, end=' ')
        
"""
0 a b c 1 2 a b c 3 a b c 
"""
```



```python
# 双层循环-内循环体中终止内循环

import string

for i in range(4):
    print(i, end=' ')

    for j, letter in enumerate(string.ascii_lowercase[:3]):
        if j == 1:
            continue
        print(letter, end=' ')
        
"""
0 a c 1 a c 2 a c 3 a c 
"""
```





# 异常处理



## 内置异常

https://docs.python.org/zh-cn/3.8/library/exceptions.html#exception-hierarchy

```python
BaseException
 +-- SystemExit               # 请求退出程序，通常由sys.exit()引发
 +-- KeyboardInterrupt       # 用户中断执行，通常是通过Ctrl+C触发
 +-- GeneratorExit            # 生成器或协程的close()方法被调用时引发
 +-- Exception                 # 所有非系统退出异常的基类

Exception
    +-- StopIteration          # 迭代器没有更多的项目可提供
    +-- StopAsyncIteration     # 异步迭代器或协程迭代完成
    +-- ArithmeticError        # 数学运算错误的基类
    |    +-- FloatingPointError # 浮点数运算异常
    |    +-- OverflowError      # 数值运算结果超出合法范围
    |    +-- ZeroDivisionError  # 除数为零
    +-- AssertionError         # 条件判断失败，assert语句失败时引发
    +-- AttributeError         # 尝试访问对象不存在的属性
    +-- BufferError            # 缓冲区操作失败
    +-- EOFError               # 输入读取遇到文件结束，没有更多数据
    +-- ImportError            # 导入模块或包失败
    |    +-- ModuleNotFoundError # 尝试导入未找到的模块
    +-- LookupError            # 查找失败的基类
    |    +-- IndexError        # 序列中索引超出范围
    |    +-- KeyError           # 映射中找不到指定的键
    +-- MemoryError            # 内存分配失败
    +-- NameError              # 名称未定义，变量或名称空间中找不到名称
    |    +-- UnboundLocalError # 访问未初始化的局部变量
    +-- OSError                # 操作系统层面的错误
    |    +-- BlockingIOError   # 非阻塞操作在阻塞模式的文件上执行
    |    +-- ChildProcessError # 子进程操作失败
    |    +-- ConnectionError   # 连接尝试失败的基类
    |    |    +-- BrokenPipeError  # 对端关闭了连接
    |    |    +-- ConnectionAbortedError # 连接被对端abort()
    |    |    +-- ConnectionRefusedError # 连接被对端拒绝
    |    |    +-- ConnectionResetError # 连接被对端重置
    |    +-- FileExistsError    # 文件已存在，无法创建
    |    +-- FileNotFoundError  # 请求的文件不存在
    |    +-- InterruptedError   # 系统调用被中断
    |    +-- IsADirectoryError  # 预期是文件但实际是目录
    |    +-- NotADirectoryError # 预期是目录但实际不是
    |    +-- PermissionError    # 没有足够的权限执行操作
    |    +-- ProcessLookupError # 进程ID不存在
    |    +-- TimeoutError       # 操作超时
    +-- ReferenceError         # 循环垃圾回收期间的弱引用回调
    +-- RuntimeError           # 未预期的一般运行时错误
    |    +-- NotImplementedError # 方法或函数尚未实现
    |    +-- RecursionError     # 最大递归深度超过限制
    +-- SyntaxError            # Python语法错误
    |    +-- IndentationError  # 缩进错误
    |         +-- TabError      # Tab和空格混合缩进
    +-- SystemError            # 解释器发现内部错误
    +-- TypeError              # 操作或函数应用于不适当类型的对象
    +-- ValueError             # 操作或函数接收到具有正确类型但不合适的值
    |    +-- UnicodeError      # Unicode相关错误的基类
    |         +-- UnicodeDecodeError # 解码Unicode字符串出错
    |         +-- UnicodeEncodeError # 编码Unicode字符串出错
    |         +-- UnicodeTranslateError # 转换Unicode字符出错
    +-- Warning                # 警告的基类，非致命错误
         +-- DeprecationWarning # 使用了已废弃的功能
         +-- PendingDeprecationWarning # 即将废弃的功能警告
         +-- RuntimeWarning    # 运行时可能有问题的情况
         +-- SyntaxWarning     # 可疑的语法，虽然合法但可能有误
         +-- UserWarning       # 用户代码生成的警告
         +-- FutureWarning     # 未来版本的Python中行为会改变
         +-- ImportWarning     # 导入模块时的警告
         +-- UnicodeWarning    # Unicode相关的警告
         +-- BytesWarning      # 字节和字符串混合操作的警告
         +-- ResourceWarning   # 资源使用相关的警告，如未关闭的文件
```



## 语法错误

语法错误又称解析错误，是学习 Python 时最常见的错误。解析器会复现出现句法错误的代码行，并用小“箭头”指向行里检测到的第一个错误。

```python
while True print('Hello world')
```

```powershell
    while True print('Hello world')
               ^
SyntaxError: invalid syntax
```



## 常见异常

即使语句或表达式使用了正确的语法，执行时仍可能触发错误。执行时检测到的错误称为 异常，异常不一定导致严重的后果。

**ZeroDivisionError**

```python
10 * (1/0)
```

```powershell
Traceback (most recent call last):
  File "c:/code/python3.8-base/test.py", line 1, in <module>
    10 * (1 / 0)
ZeroDivisionError: division by zero
```



**NameError**

```python
4 + spam * 3
```

```powershell
Traceback (most recent call last):
  File "c:/code/python3.8-base/test.py", line 1, in <module>
    4 + spam * 3
NameError: name 'spam' is not defined
```



**TypeError**

```python
"2" + 2
```

```powershell
Traceback (most recent call last):
  File "c:/code/python3.8-base/test.py", line 1, in <module>
    "2" + 2
TypeError: can only concatenate str (not "int") to str
```





错误信息的最后一行说明程序遇到了什么类型的错误。作为异常类型打印的字符串是发生的内置异常的名称。对于所有内置异常都是如此，但对于用户定义的异常则不一定如此（虽然这种规范很有用）。标准的异常类型是内置的标识符（不是保留关键字）。



## 异常处理try ... except

try 语句的工作原理如下：

- 首先，执行 try 子句 （try 和 except 关键字之间的（多行）语句）。

- 如果没有触发异常，则跳过 except 子句，try 语句执行完毕。

- 如果执行 try 子句时发生了异常，则跳过该子句中剩下的部分。如果异常的类型与 except 关键字后面的异常匹配，则执行 except 子句，然后，继续执行 try 语句之后的代码。

- 如果发生的异常不是 except 子句中列示的异常，则将其传递到外部的 try 语句中；如果没有找到处理程序，则它是一个 未处理异常，语句执行将终止。





```python
try:
    # 尝试执行的代码块
    # 这里的代码可能引发异常
    x = 1 / 0
except ZeroDivisionError:
    # 当出现 ZeroDivisionError 异常时执行
    print("除数不能为零！")
except:
    # 当出现其他类型的异常时执行
    print("出现未知异常！")
finally:
    # 无论是否出现异常，都会执行的代码块
    print("异常处理结束。")
```



还可以使用as关键字指定异常变量的名称，用于在except语句块中引用该异常。

```python
try:
    # 尝试执行的代码块
    # 这里的代码可能引发异常
    x = 1 / 0
except ZeroDivisionError as e:
    # 当出现 ZeroDivisionError 异常时执行
    print("除数不能为零：", e)
except Exception as e:
    # 当出现其他类型的异常时执行
    print("出现未知异常：", e)
finally:
    # 无论是否出现异常，都会执行的代码块
    print("异常处理结束。")
```





## else子句





## 抛出异常 raise

如果无法将异常交给合适的对象，异常将继续向上层抛出，直到被捕捉或者造成主程序报错。

```python
def test_func():
    try:
        1 / 0
    except NameError as e:
        print(e)
        print("Catch NameError in the sub-function")


try:
    test_func()
except ZeroDivisionError as e:
    print(e)
    print("Catch error in the main program")
```



使用Exception在函数内捕获完成。

```python
def test_func():
    try:
        1 / 0
    except Exception as e:
        print(e)
        print("Catch NameError in the sub-function")


try:
    test_func()
except ZeroDivisionError as e:
    print(e)
    print("Catch error in the main program")
```



使用raise抛出异常

```python
def func(x):
    if x == 0:
        raise ValueError("x不能为0")

    return x * 2


try:
    func(0)
except ValueError as e:
    print(e)
```



使用trackback输出详细堆栈信息

```python
import traceback


def func(x):
    if x == 0:
        raise ValueError("x不能为0")

    return x * 2


try:
    func(0)
except ValueError:
    traceback.print_exc()
```







## 定义清理操作 finally

`finally` 子句，用于定义在所有情况下都必须要执行的清理操作。

```python
try:
    raise KeyboardInterrupt
finally:
    print("Goodbye, world!")
```

如果存在 finally 子句，则 finally 子句是 try 语句结束前执行的最后一项任务。不论 try 语句是否触发异常，都会执行 finally 子句。以下内容介绍了几种比较复杂的触发异常情景：

- 如果执行 try 子句期间触发了某个异常，则某个 except 子句应处理该异常。如果该异常没有 except 子句处理，在 finally 子句执行后会被重新触发。

- except 或 else 子句执行期间也会触发异常。 同样，该异常会在 finally 子句执行之后被重新触发。

- 如果执行 try 语句时遇到 break,、continue 或 return 语句，则 finally 子句在执行 break、continue 或 return 语句之前执行。

- 如果 finally 子句中包含 return 语句，则返回值来自 finally 子句的某个 return 语句的返回值，而不是来自 try 子句的 return 语句的返回值。



```python
def bool_return():
    try:
        return True
    finally:
        return False


bool_return()
```



```python
def divide(x, y):
    try:
        result = x / y
    except ZeroDivisionError:
        print("division by zero!")
    else:
        print("result is", result)
    finally:
        print("executing finally clause")


divide(2, 1)


divide(2, 0)


divide("2", "1")
```

输出：

```powershell
result is 2.0
executing finally clause
division by zero!
executing finally clause
executing finally clause
Traceback (most recent call last):
  File "c:/code/python3.8-base/test.py", line 18, in <module>
    divide("2", "1")
  File "c:/code/python3.8-base/test.py", line 3, in divide
    result = x / y
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```







## 自定义异常

```python
class MyCustomError(Exception):
    def __init__(self, msg):
        self.msg = msg
        super().__init__(self.msg)


try:
    raise MyCustomError("这是我的自定义异常")
except MyCustomError as e:
    print(e)
```





## 父子异常

在处理父子异常时，要确保子类异常在父类异常之前处理，否则父类异常的处理代码可能会覆盖子类异常的处理代码。

```python
def foo():
    pass


try:
    foo()
except ValueError as e:
    print("ValueError")
except UnicodeError as e:  # except永远也捕获不到UnicodeError
    print("UnicodeError")
```









